apiVersion: v1
kind: ConfigMap
metadata:
  name: retail-store-ui-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: "prod"
  JAVA_OPTS: "-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom"
  RETAIL_UI_ENDPOINTS_CATALOG: "http://catalog:80"
  RETAIL_UI_ENDPOINTS_CARTS: "http://carts:80"
  RETAIL_UI_ENDPOINTS_ORDERS: "http://orders:80"
  RETAIL_UI_ENDPOINTS_CHECKOUT: "http://checkout:80"
